# -*- coding: utf-8 -*-
"""image_cropper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HkfoMMBnDH-3BIavtY9RCzpJaDYoVpI_
"""

from PIL import Image
import os

def crop_images(directory, image_prefix, num_images, x, y, width, height):
    for i in range(num_images):
        image_filename = f"{image_prefix}({i+38}).png"
        image_path = os.path.join(directory, image_filename)
        output_filename = f"cropped({i+38}).png"
        output_path = os.path.join("/content/drive/MyDrive/cropped_images", output_filename)
        
        try:
            # Open the image file
            image = Image.open(image_path)
            
            # Crop the image using the provided dimensions
            cropped_image = image.crop((x, y, x+width, y+height))
            
            # Save the cropped image
            cropped_image.save(output_path)
            
            print(f"Image {image_path} cropped and saved as {output_path} successfully!")
        
        except FileNotFoundError:
            print(f"Image {image_path} not found. Skipping...")
            continue

# Example usage
directory = "/content/drive/MyDrive/cloud_images"
image_prefix = "Screenshot "
num_images = 90  # Number of images to process (from Screenshot(38).png to Screenshot(127).png)
x = 75  # X-coordinate of the top-left corner of the crop region
y = 180  # Y-coordinate of the top-left corner of the crop region
width = 1220  # Width of the crop region
height = 692  # Height of the crop region

crop_images(directory, image_prefix, num_images, x, y, width, height)